import React from 'react';

const QrModal = ({ isOpen, onClose, storeName, category, storeId }) => {
  if (!isOpen) return null;

  const origin = window.location.origin;
  const storeSlug = storeName ? storeName.toString().toLowerCase().trim().replace(/\s+/g, '-').replace(/[^\w\-]+/g, '').replace(/\-\-+/g, '-') : storeId;
  const storeUrl = `${origin}/store/${storeSlug}`;
  
  // Using public QR Code generator API to ensure offline-compatible build and package safety
  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(storeUrl)}`;

  const handleDownload = async () => {
    try {
      const response = await fetch(qrUrl);
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${storeName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_qr.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      window.URL.revokeObjectURL(url);
    } catch (err) {
      alert('Failed to download QR code. You can right click the QR code image and select "Save Image As".');
    }
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Pop-up blocked! Please allow popups to print the QR Code.');
      return;
    }
    
    printWindow.document.write(`
      <html>
        <head>
          <title>Print QR Code - ${storeName}</title>
          <style>
            body {
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              height: 90vh;
              font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
              text-align: center;
              margin: 0;
              padding: 20px;
            }
            .card {
              border: 2px dashed #000;
              padding: 40px;
              border-radius: 20px;
              background-color: #fff;
              max-width: 400px;
            }
            h1 { font-size: 28px; margin-bottom: 5px; color: #111; }
            p { font-size: 16px; color: #666; margin-top: 0; margin-bottom: 25px; }
            img { border: 1px solid #ddd; padding: 15px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0,0,0,0.05); }
            .url { font-family: monospace; font-size: 14px; color: #444; margin-top: 25px; word-break: break-all; }
            .footer { margin-top: 30px; font-size: 12px; color: #999; }
          </style>
        </head>
        <body onload="window.print(); window.close();">
          <div class="card">
            <h1>${storeName}</h1>
            <p>${category} Directory | Scan to Connect</p>
            <img src="${qrUrl}" width="250" height="250" alt="Store QR Code" />
            <div class="url">${storeUrl}</div>
            <div class="footer">Generated by Ethiozone Marketplace</div>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div 
      className="modal-overlay" 
      onClick={onClose}
      style={{
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        backdropFilter: 'blur(8px)',
        WebkitBackdropFilter: 'blur(8px)',
        zIndex: 9999,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '20px'
      }}
    >
      <div 
        className="modal-content glass-panel" 
        onClick={(e) => e.stopPropagation()}
        style={{
          margin: 'auto',
          width: '90%',
          maxWidth: '450px',
          position: 'relative'
        }}
      >
        <button className="modal-close" onClick={onClose}>&times;</button>
        
        <div className="qr-modal-body">
          <h2>Storefront QR Code</h2>
          <p className="qr-modal-sub">Display, print, or download this QR code to promote your business.</p>
          
          <div className="qr-image-container">
            <img src={qrUrl} alt={`${storeName} QR Code`} className="qr-image" />
          </div>

          <div className="qr-store-info">
            <span className="qr-store-name">{storeName}</span>
            <span className="badge badge-indigo">{category}</span>
          </div>

          <div className="qr-actions">
            <button onClick={handleDownload} className="btn btn-secondary flex-grow">
              📥 Download PNG
            </button>
            <button onClick={handlePrint} className="btn btn-primary flex-grow">
              🖨️ Print Code
            </button>
          </div>
        </div>
      </div>

      <style>{`
        .qr-modal-body {
          text-align: center;
        }
        .qr-modal-sub {
          color: var(--text-secondary);
          font-size: 0.9rem;
          margin-bottom: 24px;
        }
        .qr-image-container {
          background: white;
          padding: 20px;
          border-radius: var(--radius-lg);
          display: inline-block;
          margin-bottom: 20px;
          box-shadow: 0 4px 15px rgba(0, 0, 0, 0.5);
        }
        .qr-image {
          display: block;
          max-width: 100%;
          height: auto;
        }
        .qr-store-info {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 6px;
          margin-bottom: 28px;
        }
        .qr-store-name {
          font-weight: 700;
          font-size: 1.2rem;
          color: #ffffff;
        }
        .qr-actions {
          display: flex;
          gap: 12px;
        }
        .flex-grow {
          flex: 1;
        }
      `}</style>
    </div>
  );
};

export default QrModal;
